/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxNrofPhysicalResourceBlocks (275)
#define maxSCSs (5)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
