/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Module"
 * 	found in "../M.asn1"
 * 	`asn1c -no-gen-OER`
 */

#include "BCCH-BCH-MessageType.h"

asn_per_constraints_t asn_PER_type_BCCH_BCH_MessageType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_BCCH_BCH_MessageType_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BCCH_BCH_MessageType, choice.mib),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_MIB,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mib"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_BCCH_BCH_MessageType_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* mib */
};
asn_CHOICE_specifics_t asn_SPC_BCCH_BCH_MessageType_specs_1 = {
	sizeof(struct BCCH_BCH_MessageType),
	offsetof(struct BCCH_BCH_MessageType, _asn_ctx),
	offsetof(struct BCCH_BCH_MessageType, present),
	sizeof(((struct BCCH_BCH_MessageType *)0)->present),
	asn_MAP_BCCH_BCH_MessageType_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_BCCH_BCH_MessageType = {
	"BCCH-BCH-MessageType",
	"BCCH-BCH-MessageType",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_BCCH_BCH_MessageType_constr_1, CHOICE_constraint },
	asn_MBR_BCCH_BCH_MessageType_1,
	1,	/* Elements count */
	&asn_SPC_BCCH_BCH_MessageType_specs_1	/* Additional specs */
};

