/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Module1"
 * 	found in "../m2.asn1"
 * 	`asn1c -no-gen-OER`
 */

#ifndef	_FrequencyInfoDL_SIB_H_
#define	_FrequencyInfoDL_SIB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SCS_SpecificCarrier;

/* FrequencyInfoDL-SIB */
typedef struct FrequencyInfoDL_SIB {
	long	 offsetToPointA;
	struct scs_SpecificCarrierList {
		A_SEQUENCE_OF(struct SCS_SpecificCarrier) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} scs_SpecificCarrierList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FrequencyInfoDL_SIB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FrequencyInfoDL_SIB;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SCS-SpecificCarrier.h"

#endif	/* _FrequencyInfoDL_SIB_H_ */
#include <asn_internal.h>
