/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Module"
 * 	found in "../M.asn1"
 * 	`asn1c -no-gen-OER`
 */

#ifndef	_MIB_H_
#define	_MIB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum subCarrierSpacingCommon {
	subCarrierSpacingCommon_scs15or60	= 0,
	subCarrierSpacingCommon_scs30or120	= 1
} e_subCarrierSpacingCommon;
typedef enum dmrs_TypeA_Position {
	dmrs_TypeA_Position_pos2	= 0,
	dmrs_TypeA_Position_pos3	= 1
} e_dmrs_TypeA_Position;
typedef enum cellBarred {
	cellBarred_barred	= 0,
	cellBarred_notBarred	= 1
} e_cellBarred;
typedef enum intraFreqReselection {
	intraFreqReselection_allowed	= 0,
	intraFreqReselection_notAllowed	= 1
} e_intraFreqReselection;

/* MIB */
typedef struct MIB {
	BIT_STRING_t	 systemFrameNumber;
	long	 subCarrierSpacingCommon;
	long	 ssb_SubcarrierOffset;
	long	 dmrs_TypeA_Position;
	long	 pdcch_ConfigSIB1;
	long	 cellBarred;
	long	 intraFreqReselection;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MIB_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_subCarrierSpacingCommon_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_dmrs_TypeA_Position_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_cellBarred_11;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_intraFreqReselection_14;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MIB;
extern asn_SEQUENCE_specifics_t asn_SPC_MIB_specs_1;
extern asn_TYPE_member_t asn_MBR_MIB_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _MIB_H_ */
#include <asn_internal.h>
