/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_BCCH_BCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_FrequencyInfoDL_SIB;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module Module in ../M.asn1 */
	&asn_DEF_BCCH_BCH_Message,	
	/* From module Module1 in ../m2.asn1 */
	&asn_DEF_FrequencyInfoDL_SIB,	
	0
};

