/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Module1"
 * 	found in "../m2.asn1"
 * 	`asn1c -no-gen-OER`
 */

#include "SCS-SpecificCarrier.h"

static int
memb_offsetToCarrier_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 2199)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_carrierBandwidth_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 275)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_offsetToCarrier_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 12,  12,  0,  2199 }	/* (0..2199) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_carrierBandwidth_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  1,  275 }	/* (1..275) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_SCS_SpecificCarrier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SCS_SpecificCarrier, offsetToCarrier),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_offsetToCarrier_constr_2,  memb_offsetToCarrier_constraint_1 },
		0, 0, /* No default value */
		"offsetToCarrier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SCS_SpecificCarrier, subcarrierSpacing),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_SubcarrierSpacing,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subcarrierSpacing"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SCS_SpecificCarrier, carrierBandwidth),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_carrierBandwidth_constr_4,  memb_carrierBandwidth_constraint_1 },
		0, 0, /* No default value */
		"carrierBandwidth"
		},
};
static const ber_tlv_tag_t asn_DEF_SCS_SpecificCarrier_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SCS_SpecificCarrier_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* offsetToCarrier */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -1, 0 }, /* carrierBandwidth */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 1, 0, 0 } /* subcarrierSpacing */
};
asn_SEQUENCE_specifics_t asn_SPC_SCS_SpecificCarrier_specs_1 = {
	sizeof(struct SCS_SpecificCarrier),
	offsetof(struct SCS_SpecificCarrier, _asn_ctx),
	asn_MAP_SCS_SpecificCarrier_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SCS_SpecificCarrier = {
	"SCS-SpecificCarrier",
	"SCS-SpecificCarrier",
	&asn_OP_SEQUENCE,
	asn_DEF_SCS_SpecificCarrier_tags_1,
	sizeof(asn_DEF_SCS_SpecificCarrier_tags_1)
		/sizeof(asn_DEF_SCS_SpecificCarrier_tags_1[0]), /* 1 */
	asn_DEF_SCS_SpecificCarrier_tags_1,	/* Same as above */
	sizeof(asn_DEF_SCS_SpecificCarrier_tags_1)
		/sizeof(asn_DEF_SCS_SpecificCarrier_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SCS_SpecificCarrier_1,
	3,	/* Elements count */
	&asn_SPC_SCS_SpecificCarrier_specs_1	/* Additional specs */
};

